export const PRODUCT_LIST = 'PRODUCT_LIST';
export const CLOSE_CART = 'CLOSE_CART';
export const OPEN_CART = 'OPEN_CART';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const MINUS_PRODUCT_TO_CART = 'MINUS_PRODUCT_TO_CART';
export const DELETE_PRODUCT_TO_CART = 'DELETE_PRODUCT_TO_CART';

